# Generated by Django 4.1.5 on 2024-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_content_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(upload_to='', verbose_name='main_image'),
        ),
    ]
