# Generated by Django 4.1.5 on 2024-03-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
